version: "3"
services:
  redis:
    restart: unless-stopped
    image: redis:latest
  message-broker:
    restart: unless-stopped
    image: nats:latest
  observer:
    restart: unless-stopped
    image: jesuswebdev/crypto-signals-observer:latest
    env_file:
      - ./.env
    depends_on:
      - message-broker

  candles-processor:
    restart: unless-stopped
    image: jesuswebdev/crypto-signals-candles-processor:latest
    env_file:
      - ./.env
    depends_on:
      - redis
      - message-broker
  positions-processor:
    restart: unless-stopped
    image: jesuswebdev/crypto-signals-positions-processor:latest
    env_file:
      - ./.env
    depends_on:
      - message-broker
  signals-processor:
    restart: unless-stopped
    image: jesuswebdev/crypto-signals-signals-processor:latest
    env_file:
      - ./.env
    depends_on:
      - message-broker
      - redis
  trader:
    restart: unless-stopped
    image: jesuswebdev/crypto-signals-trader:latest
    env_file:
      - ./.env
    depends_on:
      - message-broker
  account-observer:
    restart: unless-stopped
    image: jesuswebdev/crypto-signals-account-observer:latest
    env_file:
      - ./.env
