version: "3"
services:
  mongodb:
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - db_data:/data/db
  redis:
    restart: unless-stopped
    image: redis:latest
  message-broker:
    restart: unless-stopped
    image: nats:latest
  observer:
    restart: unless-stopped
    build:
      context: ./observer/
      dockerfile: ./Dockerfile
    env_file:
      - ./observer/.env
    environment:
      - MESSAGE_BROKER_SERVICE_HOST=message-broker
      - NODE_ENV=production
    depends_on: 
      - message-broker
  candles-processor:
    restart: unless-stopped
    build:
      context: ./candles-processor/
      dockerfile: ./Dockerfile
    env_file:
      - ./candles-processor/.env
    environment:
      - MESSAGE_BROKER_SERVICE_HOST=message-broker
      - MONGODB_SERVICE_HOST=mongodb
      - REDIS_SERVICE_HOST=redis
      - NODE_ENV=production
    depends_on: 
      - mongodb
      - redis
      - message-broker
  positions-processor:
    restart: unless-stopped
    build:
      context: ./positions-processor/
      dockerfile: ./Dockerfile
    env_file:
      - ./positions-processor/.env
    environment:
      - MESSAGE_BROKER_SERVICE_HOST=message-broker
      - MONGODB_SERVICE_HOST=mongodb
      - NODE_ENV=production
    depends_on: 
      - mongodb
      - message-broker
  signals-processor:
    restart: unless-stopped
    build:
      context: ./signals-processor/
      dockerfile: ./Dockerfile
    env_file:
      - ./signals-processor/.env
    environment:
      - MESSAGE_BROKER_SERVICE_HOST=message-broker
      - MONGODB_SERVICE_HOST=mongodb
      - REDIS_SERVICE_HOST=redis
      - NODE_ENV=production
    depends_on: 
      - mongodb
      - message-broker
      - redis
  trader:
    restart: unless-stopped
    build:
      context: ./trader/
      dockerfile: ./Dockerfile
    env_file:
      - ./trader/.env
    environment:
      - MESSAGE_BROKER_SERVICE_HOST=message-broker
      - MONGODB_SERVICE_HOST=mongodb
      - NODE_ENV=production
    depends_on: 
      - mongodb
      - message-broker
  account-observer:
    restart: unless-stopped
    build:
      context: ./account-observer/
      dockerfile: ./Dockerfile
    env_file:
      - ./account-observer/.env
    environment:
      - MONGODB_SERVICE_HOST=mongodb
      - NODE_ENV=production
    depends_on: 
      - mongodb
volumes:
  db_data:
