export enum EXCHANGE_TYPES {
  CANDLE_EVENTS = 'CANDLE_EVENTS',
  POSITION_EVENTS = 'POSITION_EVENTS',
  SIGNAL_EVENTS = 'SIGNAL_EVENTS'
}

export enum CANDLE_EVENTS {
  CANDLE_TICK = 'CANDLE_TICK',
  CANDLE_PROCESSED = 'CANDLE_PROCESSED'
}

export enum POSITION_EVENTS {
  POSITION_CREATED = 'POSITION_CREATED',
  POSITION_CLOSED = 'POSITION_CLOSED'
}

export enum SIGNAL_EVENTS {
  SIGNAL_CREATED = 'SIGNAL_CREATED',
  SIGNAL_CLOSED = 'SIGNAL_CLOSED'
}
